### ISSUE TITLE
Разработка по промышленным стандартам

### ISSUE THREAD

**Issue by alehinsasha** [timofeys/BigFinal#3]
- [x] Одна функциональность = одна фича и сценарии проверяющие работу этой фичи/функциональности
- [x] Использование фикстур
- [x] Повторное использование шагов (собственная библиотека шагов)
- [x] Фичи из воздуха
- [x] Детализация фичи

**Comment by alehinsasha** [comment]
**В дополнение к проверке навыка "Повторное использование шагов (собственная библиотека шагов)"**

Для подтверждения этого навыка у вас должно быть:
1. Две фичи проверяющие поступление и продажу товара.
2. В каталоге features каталог в котором вы будете хранить ваши библиотечные фичи.
3. В этом каталоге библиотечных шагов должна быть одна фича с одним универсальным (параметризованным) шагом который будет удалять документы.
4. В фичах поступления и продажи нужно использовать этот библиотечный шаг.

**Comment by alehinsasha** [comment]
Если пункт "Повторное использование шагов (собственная библиотека шагов)" реализован прошу указать в каком коммите.

**Comment by timofeys** [comment]
Для создания библиотечной фичи, поняла что нужно указать в ней - @ExportScenarios.
А как ее использование (шагов из нее ) в свою текущую фичу добавить?

**Comment by alehinsasha** [comment]
Нет. "Экспортные сценарии" - это одно, а "Повторное использование шагов" - другое. Нужно понять что функциональность "Повторное использование шагов" срабатывает во время чтения указанного каталога фич или фичи. Суть этой функциональности в том чтобы 1) прочитать шаги фич(и) 2) найти процедуры проверки шагов фич(и). Если указали каталог, то будет просканирован указанный каталог и его подкаталоги. Если указана фича, то будет просканирован каталог в котором лежит фича и его подкаталоги. И в том и другом случае дополнительно, даже в первую очаредь, сканируются каталоги указанные на закладке "Библиотеки". Т.е. процедура проверки шага может быть в другой обработке, не соответствующей фиче. Определение шага совпало, процедура найдена. Попробуйте зная это использовать эту функциоальность. Если не получиться - пишите.

**Comment by timofeys** [comment]
Если я правильно поняла, то вот реализация библиотечной фичи
