### ISSUE TITLE
Программная работа с функциональностью "Автоматизированное тестирование 1С"

### ISSUE THREAD

**Issue by alehinsasha** [timofeys/BigFinal#4]
- [x] Создать свой шаг проверяющий текст сообщения пользователю

**Comment by alehinsasha** [comment]
**В дополнение к проверке навыка "Создать свой шаг проверяющий текст предупреждения"**

Нужно реализовать свой шаг используя функциональность "Автоматизированное тестирование 1С" и свойство "ТестовоПриложение" переменной "КонтекстСохраняемый", который проверяет сообщения пользователю в момент проведения документа реализации товара. Например, если нет в сообщении текста "Не хватает товара" то реализация провелясь корректно. Или если есть текст "Не хватает товара" а товара действительно нет на остатках, то - Ок, функциональность контроля остатков проверена.

**Comment by alehinsasha** [comment]
Если есть сложности с этой задачей - пишите.

**Comment by timofeys** [comment]
При проведении продажи , сообщение выскакивает, но не могу записать его проверку в фичу способом "фича из воздуха", не видит изменения в окне сообщений. И могу только отследить что выскочило окно предупреждения...

**Comment by timofeys** [comment]
Почему то шаг в ванессе серым выделен, вроде бы видит библиотечную фичу, но почему- то не проверяет. И отладка не останавливается....Как бы ее еще проверить?

**Comment by timofeys** [comment]
Разобралась.

**Comment by alehinsasha** [comment]
Отлично!
